name: Run Practice Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go 1.26.8
              uses: actions/setup-go@v2
              with:
                  go-version: 1.26.8
            - name: Run tests of practice
              run: cd practice && go test -v ./...

            - name: Run tests with coverage of practice
              run: cd practice && go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out coverage.out
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  file: coverage.out
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: true
